### PR TITLE
Add option to show usage before description

### PR DESCRIPTION
**Pull request by mayrholu**
Solves https://github.com/tox-dev/sphinx-argparse-cli/issues/147

### CODE REVIEW

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Merge conflicts 😀

**Comment by gaborbernat** [comment]
seems CI is failing 🤔

**Comment by mayrholu** [comment]
Sorry it was the end of my day here :) now it should finally work.

**Comment by mayrholu** [comment]
@gaborbernat Thanks for all the merges!

**Pull request merged**
