### PR TITLE
Differentiate between upper and lower cases in ids

### LINKED ISSUE #31: References must differentiate between upper and lower cases
## Reproducible example

- Go to https://mdpo.readthedocs.io/en/master/cli.html#md2po--d and you will land into `md2po -d, --metadata` argument.
- Go to https://mdpo.readthedocs.io/en/master/cli.html#md2po--D and you will land at the top of the page, when there is a `md2po -D, --debug` option.

### PR DESCRIPTION
**Pull request by mondeja**
Fixes #31

### CODE REVIEW

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Can you add a changelog entry?

**Comment by mondeja** [comment]
Added in #30

**Comment by mondeja** [comment]
It was inevitable... 😆 Done in https://github.com/tox-dev/sphinx-argparse-cli/pull/32/commits/2ef33cd99ceabb8fc6921fbf281aea2714aaedcd

**Review by gaborbernat — APPROVED** [review]

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/sphinx-argparse-cli/actions/runs/1445609332

**Pull request merged**
