### PR TITLE
Don't render default values for `store_true` and `store_false` actions

### LINKED ISSUE #29: `store_true` and `store_false` options shouldn't show default value
The next argument:

```python
parser.add_argument('--no-foo', dest='foo', action='store_false', help="No foo")
```

renders "(default: `True`)" at the end, but doesn't makes sense and is very confusing.

The same for `store_true`, renders "(default: `False`)" at the end.

### PR DESCRIPTION
**Pull request by mondeja**
Fixes #29

It seems that `W503` flake8 linting failure is in conflict with Black, ~~I'm not sure how to resolve it. Is up to you.~~ I've ignored it, as [is documented in Black's flake8 compatibility docs](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#id1).

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]

**Comment by gaborbernat** [comment]
@mondeja can you add a changelog entry and release note for today https://github.com/tox-dev/sphinx-argparse-cli/blob/main/CHANGELOG.md ?

**Comment by mondeja** [comment]
Sure but I'm leaving now, let me a few hours...

**Comment by mondeja** [comment]
Added for both PRs in https://github.com/tox-dev/sphinx-argparse-cli/pull/30/commits/6f03d7ea70dd89a39d3813c38964076430cd5ff8

Btw, it seems that 1.7.0 and 1.8.0 release changes are not included in CHANGELOG

**Comment by gaborbernat** [comment]
> Btw, it seems that 1.7.0 and 1.8.0 release changes are not included in CHANGELOG

Can you add a PR to fix that?

**Review by gaborbernat — APPROVED** [review]

**Comment by mondeja** [comment]
Okei, let's see...

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/sphinx-argparse-cli/actions/runs/1445609332

**Pull request merged**
